### ISSUE TITLE
Feature Request: Ignore Device

### ISSUE THREAD

**Issue by Chioti** [rodtoll/homebridge-wireless-sensor-tag#3]
Would it be possible to add an ignore device option? I have added one of my Nest thermostats to mytaglist so that I can control it with wireless tags in the upstairs of my house. Works great, but now the problem is it appears twice in HomeKit.  Once through the HomeBridge Nest plugin and one through the wireless tag plug in.

P.S. Now testing the garage door option in ISY... thanks!

**Comment by rodtoll** [comment]
@SteliosMakrinos - Added to my TODO list. Good idea.

**Comment by jbolter** [comment]
I was going to request this same feature!

**Comment by jbolter** [comment]
@SteliosMakrinos What is the garage door option you are testing? I'm interested in this as well.

**Comment by rodtoll** [comment]
@jbolter - I believe he is referring to the garage door opener support I added to the homebridge-isy-js plugin. If you have one of these: http://www.smarthome.com/insteon-74551-garage-door-control-status-kit.html connected to an ISY device the homebridge-isy-js will represent it as a garage door opener in homebridge.

@jbolter - Got the second vote on adding an ignore option. It's on my TODO list.

**Comment by rodtoll** [comment]
@SteliosMakrinos - Added in 0.0.2 just published. See README.md for instructions on using the ignore list.

**Comment by Chioti** [comment]
@rodtoll - works perfectly!

**Comment by jbolter** [comment]
Thanks for this!
