### ISSUE TITLE
Python or ISY Polyglot Node Server Support

### ISSUE THREAD

**Issue by Chioti** [rodtoll/homebridge-wireless-sensor-tag#5]
@rodtoll I know this isn't an issue but I was wondering if you have any plans to create either a Polyglot Node Server for the Wireless Sensor Tags or python support through which someone else can do it?

**Comment by rodtoll** [comment]
At this time I have no plans to support the Polyglot server. Python is not one of my core languages. :)  

The good news is that the wireless sensor tags have a very good set of documentation for their API. So it is possible to build a library to support it.

**Comment by Chioti** [comment]
Can I use your js code as a starting point for trying to do this in Python?  I am not a programmer although I have some programming experience during the past 20 years and would treat this as a personal project/hobby.  If I get it to work well I will of course share with the ISY Polyglot community.
