### ISSUE TITLE
Feature Request: Reed Sensor Support

### ISSUE THREAD

**Issue by kenderson** [rodtoll/homebridge-wireless-sensor-tag#6]
@rodtoll - Great Work here! I use Reed Sensors all over my house for entryway notifications. I'd gladly donate a [Reed Sensor](https://store.wirelesstag.net/products/reed-kumosensor) to you if you could add support for it in this project. If that sounds good to you, shoot me your address - henderson.ken@gmail.com .

Thanks Again for the Great Work!

**Comment by kenderson** [comment]
Hey @rodtoll! Happy Holidays! I just wanted to take a moment to check in here.

Thank you again!

**Comment by rodtoll** [comment]
Hi Ken -

I've ordered one of these reed sensors and will add support once it arrives
so it should be available sometime over break.

**Comment by kenderson** [comment]
@rodtoll Awesome - thanks so much!

**Comment by kapps7** [comment]
+1 on the work and look forward to the reed. Thanks very much!

**Comment by kenderson** [comment]
@rodtoll I hope all is well! I just wanted to take a moment and check-in here. 

Thanks Again!

**Comment by rodtoll** [comment]
@kenderson - Unfortunately I wasn't able to add support before discontinuing active development. The main issue here is that the plugin polls the cloud service for status. So it's possible that between calls to check current status the reed sensor could be triggered and then returned to untriggered without the plugin noticing. So door events could be missed. Plugin would need to be re-architected to support this.
