### ISSUE TITLE
Occupancy Detected

### ISSUE THREAD

**Issue by kapps7** [rodtoll/homebridge-wireless-sensor-tag#8]
Trying to interpret these. Have the pro 2k tags connected. In the Home app, they say they are triggered - Occupancy detected. 

What does that mean ? Can these be used when they move i.e. on a door open/close ?
Thanks.

**Comment by rodtoll** [comment]
@kapps7 - I'm not sure. I don't have one of these tags. I would check the documentation on the homepage for the devices.
