### ISSUE TITLE
Info Request:  Motion Detection

### ISSUE THREAD

**Issue by abort-retry-ignore** [rodtoll/homebridge-wireless-sensor-tag#9]
How difficult would it be to add motion detection?  All the sensors support it now, as does HomeKit.  It should be possible?

**Comment by rodtoll** [comment]
@imperialjoy - This addition would not be trivial. This plugin uses polling and for motion sensing you would want to have active notification -- otherwise a motion sensing change could occur and the plugin wouldn't notice.
